codestates-seb/seb40_main_019

client/.eslintrc.json
client/package-lock.json
client/package.json
client/src/App.js
client/src/components/footer/css/footer.scss
client/src/components/footer/js/Footer.js
client/src/components/header/css/header.scss
client/src/components/header/css/nav.scss
client/src/components/header/js/Header.js
client/src/components/header/js/Nav.js
client/src/components/home/js/Home.js
client/src/components/layout/css/layout.scss
client/src/components/layout/js/Layout.js
client/src/components/main/css/main.scss
client/src/components/main/js/Main.js
client/src/index.js
client/src/redux/store.js

1. 헤더 컴포넌트 레이아웃 생성.
2. 메인 컴포넌트 레이아웃 생성.
3. 푸터 컴포넌트 레이아웃 생성.

[FE] Feat: 초기 레이아웃 설정

---

backend/appspec.yml
backend/scripts/initialize.sh
backend/scripts/server_clear.sh
backend/scripts/server_start.sh
backend/scripts/server_stop.sh
buildspec.yml

Feat: aws 파이프라인 스크립트, 설정 추가 #7

---

backend/build.gradle
backend/src/main/java/com/backend/domain/user/domain/AuthUser.java
backend/src/main/java/com/backend/global/config/error/ExceptionCode.java
backend/src/main/java/com/backend/global/config/error/GlobalExceptionHandler.java
backend/src/main/java/com/backend/global/config/security/SecurityConfig.java
backend/src/main/java/com/backend/global/config/security/exception/InvalidJwtTokenException.java
backend/src/main/java/com/backend/global/config/security/exception/JwtExceptionFilter.java
backend/src/main/java/com/backend/global/config/security/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/backend/global/config/security/handler/UserAuthenticationFailureHandler.java
backend/src/main/java/com/backend/global/config/security/handler/UserAuthenticationSuccessHandler.java
backend/src/main/java/com/backend/global/jwt/JwtAuthenticationEntryPoint.java
backend/src/main/java/com/backend/global/jwt/TokenProvider.java

-  #11 
- CustomUserDetails 수정
- 전역에러어드바이스 추가
-  Gson 의존성 추가
- 추후 JWT 관련 에러 테스트

[BE] Feat/로그인

---

client/src/App.js
client/src/pages/Products/js/Products.js

Feat/22 상품리스트

---

client/package-lock.json
client/src/App.js
client/src/components/productItem/css/productItem.scss
client/src/components/productItem/css/productItems.scss
client/src/components/productItem/js/ProductItem.js
client/src/components/productItem/js/ProductItems.js
client/src/components/sidebar/css/sidebar.scss
client/src/pages/shopProductList/css/shopProductList.scss
client/src/pages/shopProductList/js/ShopProductList.js

shop 누르면 나오는  /products 전체 페이지 레이아웃

products 전체 페이지 레이아웃

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/signin/js/SigninForm.js
client/src/pages/payment/js/Failed.js
client/src/pages/payment/js/Success.js
client/src/util/api/payment.js

[FE] Feat/65 fe 결제

---

client/src/components/shop/css/productInfoBox.scss
client/src/components/shop/js/BuyAddBtn.js
client/src/components/shop/js/ProductInfoBox.js
client/src/pages/shopProductDetail/js/ShopProductDetail.js

Feat/39 상세페이지

---

client/src/App.js
client/src/components/footer/css/footer.scss
client/src/components/main/css/main.scss
client/src/components/mypage/css/userInfo.scss
client/src/components/mypage/js/UserInfo.js
client/src/components/mypage/mypagePoint/js/MypagePoint.js
client/src/components/mypage/mypageUser/css/mypageUser.scss
client/src/components/mypage/mypageUser/js/MypageUser.js
client/src/components/mypage/mypageUserEdit/js/MypageUserEdit.js
client/src/pages/mypage/point/css/mypagePointPage.scss
client/src/pages/mypage/point/js/MypagePointPage.js
client/src/pages/mypage/user/css/mypageUserPage.scss
client/src/pages/mypage/user/js/MypageUserPage.js
client/src/pages/mypage/userEdit/css/mypageUserEditPage.scss
client/src/pages/mypage/userEdit/js/MypageUserEditPage.js
client/src/pages/oauth/OauthGoogle.js
client/src/util/api/mypageUser.js
client/src/util/api/oauthKakao.js

[FE] Feat/85 fe 마이페이지유저

---

client/data/data.json
client/src/components/shop/productOrder/css/cartList.scss
client/src/components/shop/productOrder/css/cartListItem.scss
client/src/components/shop/productOrder/css/orderSummary.scss
client/src/components/shop/productOrder/js/CartList.js
client/src/components/shop/productOrder/js/CartListItem.js
client/src/components/shop/productOrder/js/OrderSummary.js
client/src/pages/shopProductOrder/css/shopProductOrder.scss
client/src/pages/shopProductOrder/js/ShopProductOrder.js

Feat/77 상품 장바구니&결제

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/signin/js/SigninForm.js
client/src/index.js
client/src/pages/oauth/OauthGoogle.js
client/src/pages/oauth/OauthKakao.js
client/src/redux/reducers/userSlice.js
client/src/util/api/loginForm.js
client/src/util/api/oauthGoogle.js
client/src/util/api/oauthKakao.js
client/src/util/cookie/cookie.js

1. 소셜 로그인 구현
2. 로그인, 로그아웃 로직 수정 (서버 테스트X)

[FE] Feat/61 fe 소셜로그인

---

client/src/App.js
client/src/util/api/Reissue.js
client/src/util/api/loginForm.js
client/src/util/api/mypageUser.js

1. 로그인 구조 변경
2. 로그아웃 구조 변경
3. 엑세스 토큰 재발급 구조 변경

[FE] Feat: 로그인, 로그아웃, 엑세스 토큰 재발급 로직 변경

---

client/src/util/api/mypageUser.js

[FE] Feat: 새 비밀번호 확인 정규표현식 변경

---

client/src/components/productItem/css/aiProducts.scss
client/src/components/productItem/js/AIproducts.js
client/src/pages/shopProductList/js/ShopProductList.js

Feat/98 맞춤추천사료

---

client/src/components/signup/js/SignupForm.js
client/src/components/signup/js/SignupModal.js
client/src/redux/reducers/signupModalSlice.js
client/src/redux/reducers/userSlice.js
client/src/util/api/loginForm.js

Refactor/123 fe 회원가입

---

client/src/App.js
client/src/components/mypage/mypageUser/js/MypageUser.js
client/src/components/mypage/mypageUserEdit/js/MypageUserEdit.js
client/src/util/api/mypageUser.js

1. 회원 정보 조회 구현
2. 회원 정보 수정 구현
3. 회원 정보 삭제 구현

[FE] Feat: 회원 정보 조회, 수정, 삭제 구현

---

client/src/components/footer/css/footer.scss
client/src/components/productItem/js/AIproducts.js
client/src/components/shop/css/buyAddBtn.scss
client/src/components/shop/css/productInfoBox.scss
client/src/components/shop/js/ProductInfoBox.js

Feat/142 shop리팩토링

---

client/src/components/signup/js/SignupForm.js
client/src/components/signup/js/SignupModal.js

[FE] Refactor/123 fe 회원가입

---

client/src/components/signin/js/SigninForm.js
client/src/util/api/loginForm.js
client/src/util/api/oauthGoogle.js
client/src/util/api/oauthKakao.js

[FE] Refactor/124 fe 로그인

---

client/src/components/mypage/mypageUserEdit/js/MypageUserEdit.js

Refactor: 게스트 계정 비밀번호 변경 차단

---

client/src/components/mypage/mypageUser/css/deleteUserModal.scss
client/src/components/mypage/mypageUser/js/DeleteUserModal.js
client/src/components/mypage/mypageUser/js/MypageUser.js
client/src/util/api/mypageUser.js

[FE] Feat: 회원 탈퇴 확인 과정 추가

---

client/src/components/signin/css/findEmailModal.scss
client/src/components/signin/css/signinForm.scss
client/src/components/signin/js/FindEmailModal.js
client/src/components/signin/js/FindPasswordModal.js
client/src/components/signin/js/SigninForm.js
client/src/util/api/userAccount.js

[FE] Feat: 아이디 찾기 임시 구현

---

client/src/components/signin/css/findPasswordModal.scss
client/src/components/signin/js/FindEmailModal.js
client/src/components/signin/js/FindPasswordModal.js
client/src/util/api/userAccount.js

[FE] Feat: 비밀번호 찾기 임시 구현

---

client/src/components/shop/js/BuyAddBtn.js
client/src/components/shop/js/ProductInfoBox.js
client/src/pages/shopProductDetail/js/ShopProductDetail.js

[FE] Feat: 장바구니 담기 구현

---

client/src/util/api/userAccount.js

[FE]Feat: 아이디 찾기 구현

---

client/src/components/signin/js/FindPasswordModal.js
client/src/util/api/userAccount.js

[FE] Feat: 비밀번호 찾기 구현

---

client/src/components/shop/js/BuyAddBtn.js
client/src/components/shop/js/ProductInfoSmall.js
client/src/components/shop/productOrder/css/cartListItem.scss
client/src/components/shop/productOrder/css/cartQuantityBtn.scss
client/src/components/shop/productOrder/js/CartList.js
client/src/components/shop/productOrder/js/CartListItem.js
client/src/components/shop/productOrder/js/CartQuantityBtn.js
client/src/components/shop/productOrder/js/OrderSummary.js
client/src/pages/shopProductDetail/js/ShopProductDetail.js
client/src/pages/shopProductOrder/css/shopProductOrder.scss
client/src/pages/shopProductOrder/js/OrderMobileButton.js
client/src/pages/shopProductOrder/js/ShopProductOrder.js

[FE] Feat/163 fe 장바구니

---

client/src/components/shop/productOrder/js/OrderSummary.js

[FE]Fix: merge 에러 수정

---

client/src/components/payment/js/PaymentModal.js
client/src/util/api/order.js

[FE] Feat: 단품 주문, 결제 구현

---

client/src/components/mypage/mypagePoint/js/MypagePointList.js
client/src/pages/mypage/point/css/mypagePointPage.scss
client/src/pages/mypage/point/js/MypagePointPage.js
client/src/util/api/point.js

[FE] Feat: 결제 연동 준비

---

client/src/pages/payment/js/Success.js
client/src/util/api/payment.js

[FE] Feat: 결제 연동

---

client/src/components/productItem/css/aiComponent.scss
client/src/components/productItem/css/productItems.scss
client/src/components/productItem/js/AiComponent.js

Feat/177 fe ai컴포넌트

---

client/src/components/mypage/mypagePoint/js/MypagePointList.js
client/src/components/mypage/mypagePoint/js/MypagePointListItem.js
client/src/pages/shopMypageOrderList/js/ShopMypageOrderList.js

[FE] Feat: 포인트 히스토리 구현

---

client/src/components/productItem/css/aiComponent.scss
client/src/components/productItem/css/productItem.scss
client/src/components/productItem/css/productItems.scss
client/src/components/productItem/js/ProductItem.js

[FE] Fix: 상품 리스트 페이지 디자인 버그 수정

---

client/src/components/productItem/css/aiComponent.scss
client/src/components/productItem/css/productItem.scss
client/src/components/productItem/js/AiComponent.js
client/src/components/shop/css/productInfoBox.scss
client/src/components/shop/productOrder/css/cartList.scss

[FE] Fix: 상품 디테일 페이지 디자인 수정

---

client/src/components/payment/js/PaymentModal.js
client/src/components/productItem/css/aiComponent.scss
client/src/components/shop/js/BuyAddBtn.js
client/src/components/shop/js/ProductInfoBox.js
client/src/components/shop/js/ProductInfoSmall.js
client/src/components/shop/productOrder/js/OrderSummary.js
client/src/pages/shopProductDetail/js/ShopProductDetail.js
client/src/pages/shopProductOrder/js/OrderMobileButton.js

[FE] Fix/197 fe 버그수정

---

client/src/util/api/point.js
client/src/util/useFetch.js

[FE] Fix: useFetch setTimeout 제거

---

client/src/components/payment/js/PaymentModal.js
client/src/components/shop/js/BuyAddBtn.js
client/src/components/shop/js/ProductInfoSmall.js
client/src/components/shop/productOrder/js/CartList.js
client/src/components/shop/productOrder/js/CartListItem.js
client/src/pages/shopMypageOrderList/js/ShopMypageOrderList.js
client/src/pages/shopProductOrder/js/ShopProductOrder.js
client/src/util/api/order.js

[FE] Fix: 결제 정보 유효성 검사 추가

---

client/src/components/shop/productOrder/css/cartList.scss
client/src/components/shop/productOrder/js/OrderSummary.js
client/src/pages/shopProductOrder/js/OrderMobileButton.js

[FE] Fix: 선택한 상품 없이 구매 차단

---

client/src/components/header/js/Header.js
client/src/pages/shopProductOrder/css/orderMobileButton.scss

header-logo이미지에 navigation 추가 
img 바로 주면 오류나서 button추가 후 네비게이션 줌

Feat/fe 225 css수정

---

client/src/util/api/payment.js

[FE] Fix: 결제 리다이렉트 url 수정

---

client/src/components/layout/js/ShopLayout.js
client/src/components/mypage/mypagePoint/js/MypagePointList.js
client/src/components/productItem/js/ProductItems.js
client/src/components/sidebar/js/SidebarMenu.js
client/src/pages/review/js/Review.js
client/src/pages/sellerOrder/js/SellerOrder.js
client/src/pages/sellerProduct/js/SellerProducts.js
client/src/pages/sellerReview/js/SellerReview.js
client/src/pages/shopMypageOrderList/js/ShopMypageOrderList.js

[FE ]Feat: 페이지네이션 스크롤 위치 조정
